#ifndef _DEF_H_

#define _DEF_H_





//#define SLAVE_SELECT_PIN EXT1_PIN_SPI_SS_0
#define SERCOM3_SPI_PINMUX_PAD0			PIN_PA22
#define SERCOM3_SPI_PINMUX_PAD1			PIN_PA23
#define SERCOM3_SPI_PINMUX_PAD2			PIN_PA20
#define SERCOM3_SPI_PINMUX_PAD3			PIN_PA21


#define SERCOM3_SPI_nCS					SERCOM3_SPI_PINMUX_PAD2
#define SERCOM3_SPI_SCK					SERCOM3_SPI_PINMUX_PAD1
#define SERCOM3_SPI_MOSI				SERCOM3_SPI_PINMUX_PAD0
#define SERCOM3_SPI_MISO				SERCOM3_SPI_PINMUX_PAD3
#define SERCOM3_SPI_MUX_SETTING			SPI_SIGNAL_MUX_SETTING_D 


#define SERCOM2_SPI_nCS					GPIO_PA14
#define SERCOM2_SPI_SCK					GPIO_PA13
#define SERCOM2_SPI_MOSI				GPIO_PA12
#define SERCOM2_SPI_MISO				GPIO_PA15

#define SERCOM_FT8XX SERCOM2
#define FT8XX_nCS SERCOM2_SPI_nCS



#endif



